import localFont from "next/font/local";
import "./globals.css";

const iranSansRegular = localFont({
  src: "./fonts/IRANSansXRegular.ttf", // Path to regular font
  variable: "--font-iran-sans-regular", // CSS variable for regular
  weight: "400", // Regular weight (or the weight used for regular text)
});

// Load the bold version of IranSans
const iranSansBold = localFont({
  src: "./fonts/IRANSansXBold.ttf", // Path to bold font
  variable: "--font-iran-sans-bold", // CSS variable for bold
  weight: "700", // Bold weight (or the weight used for bold text)
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${iranSansRegular.variable} ${iranSansBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
