import localFont from "next/font/local";
import "./globals.css";

const iranSansRegular = localFont({
  src: "./fonts/IRANSansXRegular.ttf",
  variable: "--font-iran-sans-regular",
  weight: "400",
});

const iranSansBold = localFont({
  src: "./fonts/IRANSansXBold.ttf",
  variable: "--font-iran-sans-bold",
  weight: "700",
});

export const metadata = {
  title: "Fly List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${iranSansRegular.variable} ${iranSansBold.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
